# Generated by Django 4.2.22 on 2025-06-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_is_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Câu hỏi trong Đề thi', 'verbose_name_plural': 'Câu hỏi trong Đề thi'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='order_in_quiz',
        ),
    ]
