# Generated by Django 4.2.22 on 2025-06-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_temporary',
            new_name='is_snapshot',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('static', 'Đề thi tĩnh'), ('dynamic', 'Đề thi động')], default='static', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='template_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='quiz_app.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, through='quiz_app.QuizQuestion', to='quiz_app.question'),
        ),
        migrations.CreateModel(
            name='DynamicQuizRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quiz_app.quiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topic')),
            ],
            options={
                'verbose_name': 'Quy tắc Đề thi động',
                'verbose_name_plural': 'Quy tắc Đề thi động',
                'unique_together': {('quiz', 'topic')},
            },
        ),
    ]
