# Generated by Django 5.2.2 on 2025-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_rename_is_temporary_quiz_is_snapshot_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
