# Generated by Django 4.2.22 on 2025-06-10 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0006_userattempt_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='question_order',
            field=models.TextField(default='[]'),
        ),
    ]
